Add .npmignore to keep published package slim
timkindberg/jest-when pull request #99
Opened 2022-11-01 11:49 UTC by ericcornelissen

Create the `.npmignore` file with an allowlist of files that should be published. I went with an "allowlist" approach to avoid files added in the future, as well as files that happen to exist at the time of publishing, from being included in the published packages.

I've never used yarn when publishing a package so I'm not 100% sure this will work, but from what I could find online it seems this should work.

---

For reference, this is what the installed package currently looks like:

```shell
$ npm ls jest-when
example@3.1.0 /path/to/example
└── jest-when@3.5.2

$ l node_modules/jest-when
.eslintignore
.eslintrc
LICENSE
package.json
README.md
src
stryker.conf.js
.tool-versions
.travis.yml

$ l node_modules/jest-when/src
when.js
when.test.js
```

And here's what it would look like after this change:

```shell
$ l node_modules/jest-when
LICENSE
package.json
README.md
src

$ l node_modules/jest-when/src 
when.js
```

2022-11-07 13:41 UTC, timkindberg commented on .npmignore
> +!src/**/*.test.js
This doesn't seem to exclude the .test.js file properly. I ran `npm pack` and it was still there. I'm also thinking like there is not much unnecessary files in the npm package, so this is not super important. But I'm willing to merge it if you get this test exclusion working.

2022-11-07 17:05 UTC, joebowbeer commented
In my experience the best approach is to list exactly the files you want in package.files

Read [For the love of god, don't use .npmignore](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d)


From one of the comments:

> As per this [thread](https://github.com/npm/npm/issues/4479), it is important to note that .npmignore only works when placed within the whitelisted folders in “files”.

2022-11-07 17:15 UTC, joebowbeer requested changes
In my experience the best approach is to list exactly the files you want in package.files

Read [For the love of god, don't use .npmignore](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d)

From one of the comments:

> As per this [thread](https://github.com/npm/npm/issues/4479), it is important to note that .npmignore only works when placed within the whitelisted folders in “files” [...] otherwise npm will (ironically) ignore your ignores.

2022-11-08 00:50 UTC, closed without merging

2022-11-08 16:19 UTC, joebowbeer commented
@ericcornelissen for future reference, `npm pack` is a good way to examine which files will be published